### ISSUE TITLE
AWS_SHARED_CREDENTIALS_FILE Overwritten By Default

### ISSUE THREAD

**Issue by yhakbar** [gjbae1212/gossm#45]
I believe `AWS_SHARED_CREDENTIALS_FILE` is being overwritten by default [here](https://github.com/gjbae1212/gossm/blob/961c577b069a278c239c7c390da29a167437397c/cmd/root.go#L112-L133) in order to support the new MFA feature added recently.

Would it be possible to make this an optional feature? This makes the application interact with the AWS SDK in an unexpected fashion.

In order to avoid this, users have to `export AWS_SHARED_CREDENTIALS_FILE=$HOME/.aws/credentials`, which forces the shared credentials file to be the default expected for use with the AWS SDK for go.

**Comment by gjbae1212** [comment]
mfa credential doesn’t set default credential forcibly.

default credential has used it in default.
But if mfa credential file is to exist and to validate, used it.

**Comment by yhakbar** [comment]
@gjbae1212 if a user does not set `AWS_SHARED_CREDENTIALS_FILE`, then the default behavior for the golang AWS SDK is not used (`gossm` doesn't try to use `$HOME/.aws/credentials`, but instead replaces the value with `$HOME/.aws/credentials_mfa` on this line https://github.com/gjbae1212/gossm/blob/961c577b069a278c239c7c390da29a167437397c/cmd/root.go#L117).

**Comment by gjbae1212** [comment]
you should read more than code.
https://github.com/gjbae1212/gossm/blob/dd5f3c6b0e0898bb496c8101a83cd98a991afd7d/cmd/root.go#L156

**Comment by yhakbar** [comment]
When attempting to use `gossm`, I get the following error:

```
[err] [err][cmd.initConfig:209] [err][internal.NewSharedConfig:61] failed to load assume role *my role arn*, of profile default, <nil>
```

If I run this, the error goes away:

```bash
export AWS_SHARED_CREDENTIALS_FILE=$HOME/.aws/credentials
```

In my setup, I'm performing role assumption and handling MFA outside of `gossm`.

This is what my `~/.aws/credentials` file looks like:

```toml
[default]
aws_session_token     = session token
aws_access_key_id     = temporary access key id
aws_secret_access_key = temporary secret key

[my-profile]
role_arn       = role arn
source_profile = default
```

This is what my `~/.aws/config` file looks like:

```toml
[default]
output     = json
mfa_serial = mfa arn

[profile my-profile]
role_arn       = role arn
source_profile = default
```

Let me know if you think I'm using `gossm` wrong. Thanks for your help!
